// Replace with your deployed Google Apps Script Web App URL
// See: scripts/google-apps-script.gs for setup instructions
export const APPS_SCRIPT_URL = 'YOUR_APPS_SCRIPT_URL';

export const countryCodes = [
  { code: '+91',  country: 'India'        },
  { code: '+971', country: 'UAE'          },
  { code: '+1',   country: 'USA / Canada' },
  { code: '+44',  country: 'UK'           },
  { code: '+65',  country: 'Singapore'    },
  { code: '+61',  country: 'Australia'    },
  { code: '+93',  country: 'Afghanistan'  },
  { code: '+973', country: 'Bahrain'      },
  { code: '+880', country: 'Bangladesh'   },
  { code: '+32',  country: 'Belgium'      },
  { code: '+55',  country: 'Brazil'       },
  { code: '+86',  country: 'China'        },
  { code: '+20',  country: 'Egypt'        },
  { code: '+33',  country: 'France'       },
  { code: '+49',  country: 'Germany'      },
  { code: '+852', country: 'Hong Kong'    },
  { code: '+62',  country: 'Indonesia'    },
  { code: '+353', country: 'Ireland'      },
  { code: '+972', country: 'Israel'       },
  { code: '+39',  country: 'Italy'        },
  { code: '+81',  country: 'Japan'        },
  { code: '+962', country: 'Jordan'       },
  { code: '+254', country: 'Kenya'        },
  { code: '+965', country: 'Kuwait'       },
  { code: '+60',  country: 'Malaysia'     },
  { code: '+960', country: 'Maldives'     },
  { code: '+52',  country: 'Mexico'       },
  { code: '+977', country: 'Nepal'        },
  { code: '+31',  country: 'Netherlands'  },
  { code: '+64',  country: 'New Zealand'  },
  { code: '+234', country: 'Nigeria'      },
  { code: '+968', country: 'Oman'        },
  { code: '+92',  country: 'Pakistan'     },
  { code: '+63',  country: 'Philippines'  },
  { code: '+974', country: 'Qatar'        },
  { code: '+966', country: 'Saudi Arabia' },
  { code: '+27',  country: 'South Africa' },
  { code: '+82',  country: 'South Korea'  },
  { code: '+94',  country: 'Sri Lanka'    },
  { code: '+46',  country: 'Sweden'       },
  { code: '+41',  country: 'Switzerland'  },
  { code: '+66',  country: 'Thailand'     },
  { code: '+90',  country: 'Turkey'       },
  { code: '+380', country: 'Ukraine'      },
  { code: '+84',  country: 'Vietnam'      },
  { code: '+967', country: 'Yemen'        },
];
